<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="3698" started-at="2020-08-19T03:17:38Z" finished-at="2020-08-19T03:17:41Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="3698" started-at="2020-08-19T03:17:38Z" finished-at="2020-08-19T03:17:41Z">
      <class name="webdriverMaven.LoginTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:webdriverMaven.LoginTest@20d3d15a]" name="setUp" is-config="true" duration-ms="5491" started-at="2020-08-19T03:17:32Z" finished-at="2020-08-19T03:17:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="doLogin()[pri:0, instance:webdriverMaven.LoginTest@20d3d15a]" name="doLogin" duration-ms="3644" started-at="2020-08-19T03:17:38Z" finished-at="2020-08-19T03:17:41Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[fail test to check jenkin]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: fail test to check jenkin
at org.testng.Assert.fail(Assert.java:96)
at webdriverMaven.LoginTest.doLogin(LoginTest.java:33)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doLogin -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:webdriverMaven.LoginTest@20d3d15a]" name="tearDown" is-config="true" duration-ms="3048" started-at="2020-08-19T03:17:42Z" finished-at="2020-08-19T03:17:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- webdriverMaven.LoginTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
